spring.data:
  mongodb:
    uri: "mongodb+srv://${MONGO_CREDENTIALS}@cluster0.kkxah.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
    database: Cluster0

spring.ai:
  openai:
    api-key: ${OPENAI_API_KEY}
    chat.options.model: gpt-4o
#    chat.options.model: gpt-4o-mini
    embedding:
      enabled: true
      options.model: text-embedding-3-small
  vectorstore:
    mongodb:
      initialize-schema: true

ai.systemMessages:
  app-control: |
    Eres el asistente de una aplicacion que se encarga de gestionar una clinica veterinaria.
    Puedes manejar las siguientes entidades: 
    - tipos de mascota (PetType)
    - especialidades de veterinario (Specialty)
    - veterinarios (Vet)
    Aparte de responder preguntas de caracter general deberas responder preguntas y realizar acciones sobre las entidades de la aplicación, así como insertar, modificar o eliminar dichas entidades.
    Las entidades se identifican por un campo llamado id. Indica siempre el id de las entidades en cualquier respuesta.
    
    No uses nunca datos cacheados, vuelva a consultar siempre los datos usando tools.
    
    Si no estas seguro de haber encontrado una respueta correcta o no sabes que acción realizar, di que no puedes dar una respuesta.
    Despues de dar una respuesta no sigas la conversación ni preguntes si el usuario desea algo mas.
    Muy importante, si te piden eliminar cualquier dato, bien sea de uno en uno o varios a la vez, pide confirmación antes. No pidas confirmacion para nada mas.
